# docker-compose up -d
# docker update --restart=no $(docker ps -a -q) 
# docker update --restart=no my-container
# docker exec -it [container id] /bin/bash
version: '3.8'

services:
  redis-7.2:
    image: redis:7.2
    ports:
      - ${REDIS_BINDING_PORT}:${REDIS_PORT}
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_DEFAULT_CONFIG_FILE}:/usr/local/etc/redis/redis.conf
    restart: always

