# docker-compose.yml
# docker-compose up -d
version: '3.8'
services:
  mariadb-11:
    image: mariadb:11
    container_name: mariadb-11
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /c/Users/Qone/repositories/docker/mount/mariadb-11/data:/var/lib/mysql
      - /c/Users/Qone/repositories/docker/mount/mariadb-11/conf:/etc/mysql/conf.d
      - /c/Users/Qone/repositories/docker/mount/mariadb-11/backup:/root/backup
    environment:
      MARIADB_ROOT_PASSWORD: root
      TZ: "Asia/Seoul"
