FROM redis:7.2
EXPOSE 6379
VOLUME [ "/c/Users/Qone/repositories/docker/mount/redis-7.2/data", "/data" ]
VOLUME [ "/c/Users/Qone/repositories/docker/mount/redis-7.2/redis.conf", "/usr/local/etc/redis/redis.conf" ]
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
